### 1. Регистрация нового пользователя
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "nickname": "android_hero",
  "password": "pass",
  "firstName": "Roman",
  "lastName": "G"
}

### 2. Вход (Логин) через Basic Auth
POST http://localhost:8080/api/login
Authorization: Basic android_hero pass