spring.application.name=EchoServer

spring.datasource.url=jdbc:postgresql://localhost:5432/EchoDB
spring.datasource.username=postgres
spring.datasource.password=rogalik1

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

